## pdns_conf
#
# The path to the file that we need to write with configuration. It is recommended
# to use a 'drop-in' config file in the pdns.d directory and set the `include-dir`
# directive in the main pdns.conf
pdns_conf: /etc/powerdns/pdns.conf.d/sysrepo.conf
